apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gohy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gohy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gohy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gohy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gohy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vtak-tenant/rhtap-demo-app/hacbs-test-project-gohy@sha256:61106a420796f54d57acb03c3e2c6917b1c4c9532f48221a80fada28e942e6a5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
