apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gohy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vtak-tenant/rhtap-demo-app/hacbs-test-project-gohy@sha256:8a3d77b79657a49fa89fb32d09e54776af0cee85959053fb113f7b40c41e876d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
