apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gohy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vtak-tenant/rhtap-demo-app/hacbs-test-project-gohy@sha256:61106a420796f54d57acb03c3e2c6917b1c4c9532f48221a80fada28e942e6a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
